name: flutter_controle
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  fluttertoast: ^8.2.4
  google_sign_in: ^6.1.0
  google_sign_in_web: ^0.12.4+3
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/profile.png
    - images/avatar.jpg
    - images/application.jpg
