// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoj2G0BSu6E2lm8RW1nN77lo3t5f5IdNo',
    appId: '1:1092547324418:web:e9e4345a35caaa876e151b',
    messagingSenderId: '1092547324418',
    projectId: 'flutter-with-asmae',
    authDomain: 'flutter-with-asmae.firebaseapp.com',
    storageBucket: 'flutter-with-asmae.firebasestorage.app',
    measurementId: 'G-GCDSCXN36V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXueu4HSHGtQH1gJLAeeH6-aeTm_aEuoU',
    appId: '1:1092547324418:android:e638f7249183e2ea6e151b',
    messagingSenderId: '1092547324418',
    projectId: 'flutter-with-asmae',
    storageBucket: 'flutter-with-asmae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6_64H1ifxcVbLGUQVGiTYzZadRvHluWI',
    appId: '1:1092547324418:ios:78294d8b8e19e0096e151b',
    messagingSenderId: '1092547324418',
    projectId: 'flutter-with-asmae',
    storageBucket: 'flutter-with-asmae.firebasestorage.app',
    iosBundleId: 'com.example.flutterControle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6_64H1ifxcVbLGUQVGiTYzZadRvHluWI',
    appId: '1:1092547324418:ios:78294d8b8e19e0096e151b',
    messagingSenderId: '1092547324418',
    projectId: 'flutter-with-asmae',
    storageBucket: 'flutter-with-asmae.firebasestorage.app',
    iosBundleId: 'com.example.flutterControle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoj2G0BSu6E2lm8RW1nN77lo3t5f5IdNo',
    appId: '1:1092547324418:web:cbb6ede21e787ecf6e151b',
    messagingSenderId: '1092547324418',
    projectId: 'flutter-with-asmae',
    authDomain: 'flutter-with-asmae.firebaseapp.com',
    storageBucket: 'flutter-with-asmae.firebasestorage.app',
    measurementId: 'G-K2KDGW5DPH',
  );
}
